<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \AHT\ProductTag\Block\Customer\ListTags $block */
?>
<?php if (count($block->getTags())) : ?>
<div class="table-wrapper tags">
    <table class="data table table-tags" id="my-tags-table">
        <caption class="table-caption"><?= $block->escapeHtml(__('Product Tags')) ?></caption>
        <thead>
            <tr>
                <th scope="col" class="col item"><?= $block->escapeHtml(__('Product Name')) ?></th>
                <th scope="col" class="col tag"><?= $block->escapeHtml(__('Tag')) ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($block->getTags() as $tag) : ?>
            <tr>
                <td data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>" class="col name">
                    <?= $block->getProductById($tag->getProductId())->getName() ?>
                </td>
                <td data-th="<?= $block->escapeHtmlAttr(__('Tag')) ?>" class="col tag">
                    <?= $block->escapeHtml($tag->getTag()) ?>
                </td>
                <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
                    <a href="<?= $block->getFrontendUrl().'/'.$tag->getTag(); ?>" class="action more">
                        <span><?= $block->escapeHtml(__('See Details')) ?></span>
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php if ($block->getToolbarHtml()) : ?>
<div class="toolbar products-tags-toolbar bottom">
    <?= $block->getToolbarHtml() ?>
</div>
<?php endif; ?>
<?php else : ?>
<div class="message info empty"><span><?= $block->escapeHtml(__('You have submitted no tags.')) ?></span></div>
<?php endif; ?>
<div class="actions-toolbar">
    <div class="secondary">
        <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
            <span><?= $block->escapeHtml(__('Back')) ?></span>
        </a>
    </div>
</div>